-- ============================================================
-- CLINICAL HUB · RENUMERAR LAS MEJORAS (rama feedback_ia, 2026-09-26)
-- Paula pidió este orden. Solo cambia el número (id) de cada mejora
-- y, con él, el de sus enlaces, personas e historial. No borra nada.
--
--   Insuficiencia cardíaca descompensada   5 → 1
--   Insuficiencia cardíaca crónica         4 → 2
--   Equipo de apoyo médico                 1 → 3
--   Sepsis                                 3 → 4
--   Interfaz/estética                      2 → 5
--
-- Los enlaces quedan con ON UPDATE CASCADE: si algún día se vuelve a
-- renumerar, las tablas que apuntan a la mejora se actualizan solas.
-- ============================================================

-- 1. Soltar los enlaces para poder mover los números
alter table public.mejora_ia_tema      drop constraint mejora_ia_tema_mejora_id_fkey;
alter table public.mejora_ia_persona   drop constraint mejora_ia_persona_mejora_id_fkey;
alter table public.mejora_ia_historial drop constraint mejora_ia_historial_mejora_id_fkey;
alter table public.mejoras_ia alter column id set generated by default;

-- 2. El cambio, en dos saltos (primero +1000) para que ningún número choque
update public.mejoras_ia          set id        = id + 1000        where id        between 1 and 5;
update public.mejora_ia_tema      set mejora_id = mejora_id + 1000 where mejora_id between 1 and 5;
update public.mejora_ia_persona   set mejora_id = mejora_id + 1000 where mejora_id between 1 and 5;
update public.mejora_ia_historial set mejora_id = mejora_id + 1000 where mejora_id between 1 and 5;

update public.mejoras_ia set id =
  case id when 1005 then 1 when 1004 then 2 when 1001 then 3 when 1003 then 4 when 1002 then 5 end
  where id between 1001 and 1005;
update public.mejora_ia_tema set mejora_id =
  case mejora_id when 1005 then 1 when 1004 then 2 when 1001 then 3 when 1003 then 4 when 1002 then 5 end
  where mejora_id between 1001 and 1005;
update public.mejora_ia_persona set mejora_id =
  case mejora_id when 1005 then 1 when 1004 then 2 when 1001 then 3 when 1003 then 4 when 1002 then 5 end
  where mejora_id between 1001 and 1005;
update public.mejora_ia_historial set mejora_id =
  case mejora_id when 1005 then 1 when 1004 then 2 when 1001 then 3 when 1003 then 4 when 1002 then 5 end
  where mejora_id between 1001 and 1005;

-- 3. Volver a amarrar los enlaces, ahora con ON UPDATE CASCADE
alter table public.mejora_ia_tema      add constraint mejora_ia_tema_mejora_id_fkey
  foreign key (mejora_id) references public.mejoras_ia(id) on update cascade;
alter table public.mejora_ia_persona   add constraint mejora_ia_persona_mejora_id_fkey
  foreign key (mejora_id) references public.mejoras_ia(id) on update cascade;
alter table public.mejora_ia_historial add constraint mejora_ia_historial_mejora_id_fkey
  foreign key (mejora_id) references public.mejoras_ia(id) on update cascade;

-- 4. El contador sigue después de la última: la próxima mejora será la #6
alter table public.mejoras_ia alter column id set generated always;
select setval(pg_get_serial_sequence('public.mejoras_ia', 'id'), (select max(id) from public.mejoras_ia));
